#pragma once
#include <windows.h> 

const LPCWSTR staticImage[] = {
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                        O                                                           ",
	L"                                                      /   \\                                                         ",
	L"                                                     |     |                                                        ",
	L"                                                      \\ _ /                                                         ",
	L"                                                        |                                                           ",
	L"                                            __________/   \\ _________                                               ",
	L"                                                     |     |                                                        ",
	L"                                                      \\ _ /                                                          ",
	L"                                                       / \\                                                          ",
	L"                                                                                                                      ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                       (A) Left            (N) Game A      (M) Game B           (D) Right                           ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
	L"                                                                                                                    ",
};

LPCWSTR limbsImages[][30] = {
	{
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
	L"                                       \\_/           |     |      \\_/                                               ",
	L"                                         \\            \\ _ /        |                                                ",
	L"                                          \\             |           \\                                               ",
	L"                                           \\__________/   \\ _________|                                              ",
		nullptr,
		nullptr,
	L"                                                  O   _/ \\                                                          ",
	L"                                                   \\/     |                                                         ",
	L"                                                          ==O                                                       ",
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
	},
	{
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
	L"                                          \\_/        |     |         \\_/                                            ",
	L"                                           |          \\ _ /           |                                             ",
	L"                                           |            |             |                                             ",
	L"                                           |__________/   \\ _________/                                              ",
		nullptr,
		nullptr,
	L"                                                       / \\                                                          ",
	L"                                                      |   |                                                         ",
	L"                                                    O==   ==O                                                       ",
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
	},
	{
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
	L"                                             \\_/     |     |            \\_/                                         ",
	L"                                             /        \\ _ /             /                                           ",
	L"                                            /           |              /                                            ",
	L"                                           /__________/   \\ __________/                                             ",
		nullptr,
		nullptr,
	L"                                                       / \\_  O                                                      ",
	L"                                                      |    \\/                                                       ",
	L"                                                    O==                                                             ",
		nullptr,
		nullptr,
		nullptr,
		nullptr,
		nullptr,
	}
};

const LPCWSTR crushImages[][6] = {
	{
	L"     !",
	L"    H ",
	L"   S  ",
	L"  U   ",
	L" R    ",
	L"C     ",
	},
	{
	L"(   \\|/   ",
	L"    -*-  )",
	L"    /|\\   ",
		nullptr,
		nullptr,
		nullptr,
	},
	{
	L"   \\|/  )",
	L"   -*-   ",
	L"(  /|\\   ",
		nullptr,
		nullptr,
		nullptr,
	},
};


